---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: About
  label: About
  create: documents
  match: "*.md"
  templates:
  - page
  - page
- type: directory
  path: Membership
  label: Membership
  create: documents
  match: "*.md"
  templates:
  - page
- type: directory
  path: Values
  label: Values
  create: all
  match: "**/*"
  templates:
  - blog-post
- type: directory
  path: ''
  label: Swarm Ecosystem
  create: all
  match: "**/*"
- type: document
  path: sidebars.json
  label: Sidebar
  read_only: false
upload_dir: static/img
public_path: "/img"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: build
  install_dependencies_command: yarn install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn start
